name = "oceaniavpn"
main = "src/index.py"
compatibility_date = "2026-08-16"

compatibility_flags = ["python_workers"]

[vars]
REPO_OWNER = "OceaniaVPN"
REPO_NAME = "OceaniaVPN"
CONFIGS_FOLDER = "configs"
BRANCH = "main"
