name = "oceaniavpn"
main = "src/index.js"
compatibility_date = "2026-08-16"

[build]
command = "npm install"

[vars]
CONFIG_REPO_OWNER = "OceaniaVPN"
CONFIG_REPO_NAME = "StekloVPN"
CONFIGS_FOLDER = "configs"
BRANCH = "main"

[[kv_namespaces]]
binding = "BOT_STATE"
id = "e56a18bce1624f87bc03b8de27544eb7"
