export const COUNTRIES = [
// Европа
{ keys: ["al", "albania", "албания", "тирана"], flag: "🇦🇱", name: "Албания" },
{ keys: ["ad", "andorra", "андорра", "андорра-ла-велья"], flag: "🇦🇩", name: "Андорра" },
{ keys: ["at", "austria", "австрия", "вена"], flag: "🇦🇹", name: "Австрия" },
{ keys: ["by", "belarus", "беларусь", "минск"], flag: "🇧🇾", name: "Беларусь" },
{ keys: ["be", "belgium", "бельгия", "брюссель"], flag: "🇧🇪", name: "Бельгия" },
{ keys: ["ba", "bosnia", "босния", "сараево"], flag: "🇧🇦", name: "Босния и Герцеговина" },
{ keys: ["bg", "bulgaria", "болгария", "софия"], flag: "🇧🇬", name: "Болгария" },
{ keys: ["hr", "croatia", "хорватия", "загреб"], flag: "🇭🇷", name: "Хорватия" },
{ keys: ["cy", "cyprus", "кипр", "никосия"], flag: "🇨🇾", name: "Кипр" },
{ keys: ["cz", "czechia", "чехия", "прага"], flag: "🇨🇿", name: "Чехия" },
{ keys: ["dk", "denmark", "дания", "копенгаген"], flag: "🇩🇰", name: "Дания" },
{ keys: ["ee", "estonia", "эстония", "таллин"], flag: "🇪🇪", name: "Эстония" },
{ keys: ["fi", "finland", "финляндия", "хельсинки"], flag: "🇫🇮", name: "Финляндия" },
{ keys: ["fr", "france", "франция", "париж"], flag: "🇫🇷", name: "Франция" },
{ keys: ["de", "germany", "германия", "берлин"], flag: "🇩🇪", name: "Германия" },
{ keys: ["gr", "greece", "греция", "афины"], flag: "🇬🇷", name: "Греция" },
{ keys: ["hu", "hungary", "венгрия", "будапешт"], flag: "🇭🇺", name: "Венгрия" },
{ keys: ["is", "iceland", "исландия", "рейкьявик"], flag: "🇮🇸", name: "Исландия" },
{ keys: ["ie", "ireland", "ирландия", "дублин"], flag: "🇮🇪", name: "Ирландия" },
{ keys: ["it", "italy", "италия", "рим"], flag: "🇮🇹", name: "Италия" },
{ keys: ["lv", "latvia", "латвия", "рига"], flag: "🇱🇻", name: "Латвия" },
{ keys: ["li", "liechtenstein", "лихтенштейн", "вадуц"], flag: "🇱🇮", name: "Лихтенштейн" },
{ keys: ["lt", "lithuania", "литва", "вильнюс"], flag: "🇱🇹", name: "Литва" },
{ keys: ["lu", "luxembourg", "люксембург"], flag: "🇱🇺", name: "Люксембург" },
{ keys: ["mt", "malta", "мальта", "валлетта"], flag: "🇲🇹", name: "Мальта" },
{ keys: ["md", "moldova", "молдова", "кишинев"], flag: "🇲🇩", name: "Молдова" },
{ keys: ["mc", "monaco", "монако"], flag: "🇲🇨", name: "Монако" },
{ keys: ["me", "montenegro", "черногория", "подгорица"], flag: "🇲🇪", name: "Черногория" },
{ keys: ["nl", "netherlands", "нидерланды", "амстердам"], flag: "🇳🇱", name: "Нидерланды" },
{ keys: ["mk", "north macedonia", "северная македония", "скопье"], flag: "🇲🇰", name: "Северная Македония" },
{ keys: ["no", "norway", "норвегия", "осло"], flag: "🇳🇴", name: "Норвегия" },
{ keys: ["pl", "poland", "польша", "варшава"], flag: "🇵🇱", name: "Польша" },
{ keys: ["pt", "portugal", "португалия", "лиссабон"], flag: "🇵🇹", name: "Португалия" },
{ keys: ["ro", "romania", "румыния", "бухарест"], flag: "🇷🇴", name: "Румыния" },
{ keys: ["ru", "russia", "россия", "москва"], flag: "🇷🇺", name: "Россия" },
{ keys: ["sm", "san marino", "сан-марино"], flag: "🇸🇲", name: "Сан-Марино" },
{ keys: ["rs", "serbia", "сербия", "белград"], flag: "🇷🇸", name: "Сербия" },
{ keys: ["sk", "slovakia", "словакия", "братислава"], flag: "🇸🇰", name: "Словакия" },
{ keys: ["si", "slovenia", "словения", "любляна"], flag: "🇸🇮", name: "Словения" },
{ keys: ["es", "spain", "испания", "мадрид"], flag: "🇪🇸", name: "Испания" },
{ keys: ["se", "sweden", "швеция", "стокгольм"], flag: "🇸🇪", name: "Швеция" },
{ keys: ["ch", "switzerland", "швейцария", "берн"], flag: "🇨🇭", name: "Швейцария" },
{ keys: ["ua", "ukraine", "украина", "киев"], flag: "🇺🇦", name: "Украина" },
{ keys: ["gb", "uk", "великобритания", "лондон"], flag: "🇬🇧", name: "Великобритания" },
{ keys: ["va", "vatican", "ватикан"], flag: "🇻🇦", name: "Ватикан" },
// Азия
{ keys: ["af", "afghanistan", "афганистан", "кабул"], flag: "🇦🇫", name: "Афганистан" },
{ keys: ["am", "armenia", "армения", "ереван"], flag: "🇦🇲", name: "Армения" },
{ keys: ["az", "azerbaijan", "азербайджан", "баку"], flag: "🇦🇿", name: "Азербайджан" },
{ keys: ["bh", "bahrain", "бахрейн", "манама"], flag: "🇧🇭", name: "Бахрейн" },
{ keys: ["bd", "bangladesh", "бангладеш", "дакка"], flag: "🇧🇩", name: "Бангладеш" },
{ keys: ["bt", "bhutan", "бутан", "тхимпху"], flag: "🇧🇹", name: "Бутан" },
{ keys: ["bn", "brunei", "бруней", "бандар-сери-бегаван"], flag: "🇧🇳", name: "Бруней" },
{ keys: ["kh", "cambodia", "камбоджа", "пномпень"], flag: "🇰🇭", name: "Камбоджа" },
{ keys: ["cn", "china", "китай", "пекин"], flag: "🇨🇳", name: "Китай" },
{ keys: ["ge", "georgia", "грузия", "тбилиси"], flag: "🇬🇪", name: "Грузия" },
{ keys: ["in", "india", "индия", "нью-дели"], flag: "🇮🇳", name: "Индия" },
{ keys: ["id", "indonesia", "индонезия", "джакарта"], flag: "🇮🇩", name: "Индонезия" },
{ keys: ["ir", "iran", "иран", "тегеран"], flag: "🇮🇷", name: "Иран" },
{ keys: ["iq", "iraq", "ирак", "багдад"], flag: "🇮🇶", name: "Ирак" },
{ keys: ["il", "israel", "израиль", "иерусалим"], flag: "🇮🇱", name: "Израиль" },
{ keys: ["jo", "jordan", "иордания", "амман"], flag: "🇯🇴", name: "Иордания" },
{ keys: ["kz", "kazakhstan", "казахстан", "астана"], flag: "🇰🇿", name: "Казахстан" },
{ keys: ["kw", "kuwait", "кувейт", "эль-кувейт"], flag: "🇰🇼", name: "Кувейт" },
{ keys: ["kg", "kyrgyzstan", "кыргызстан", "бишкек"], flag: "🇰🇬", name: "Кыргызстан" },
{ keys: ["la", "laos", "лаос", "вьентьян"], flag: "🇱🇦", name: "Лаос" },
{ keys: ["lb", "lebanon", "ливан", "бейрут"], flag: "🇱🇧", name: "Ливан" },
{ keys: ["my", "malaysia", "малайзия", "куала-лумпур"], flag: "🇲🇾", name: "Малайзия" },
{ keys: ["mv", "maldives", "мальдивы", "мале"], flag: "🇲🇻", name: "Мальдивы" },
{ keys: ["mn", "mongolia", "монголия", "улан-батор"], flag: "🇲🇳", name: "Монголия" },
{ keys: ["mm", "myanmar", "мьянма", "нейпьидо"], flag: "🇲🇲", name: "Мьянма" },
{ keys: ["np", "nepal", "непал", "катманду"], flag: "🇳🇵", name: "Непал" },
{ keys: ["om", "oman", "оман", "мускат"], flag: "🇴🇲", name: "Оман" },
{ keys: ["pk", "pakistan", "пакистан", "исламабад"], flag: "🇵🇰", name: "Пакистан" },
{ keys: ["ph", "philippines", "филиппины", "манила"], flag: "🇵🇭", name: "Филиппины" },
{ keys: ["qa", "qatar", "катар", "доха"], flag: "🇶🇦", name: "Катар" },
{ keys: ["sa", "saudi arabia", "саудовская аравия", "эр-рияд"], flag: "🇸🇦", name: "Саудовская Аравия" },
{ keys: ["sg", "singapore", "сингапур"], flag: "🇸🇬", name: "Сингапур" },
{ keys: ["kr", "south korea", "южная корея", "сеул"], flag: "🇰🇷", name: "Южная Корея" },
{ keys: ["lk", "sri lanka", "шри-ланка", "шри-джаяварденепура-кота"], flag: "🇱🇰", name: "Шри-Ланка" },
{ keys: ["sy", "syria", "сирия", "дамаск"], flag: "🇸🇾", name: "Сирия" },
{ keys: ["tj", "tajikistan", "таджикистан", "душанбе"], flag: "🇹🇯", name: "Таджикистан" },
{ keys: ["th", "thailand", "таиланд", "бангкок"], flag: "🇹🇭", name: "Таиланд" },
{ keys: ["tl", "timor-leste", "восточный тимор", "дили"], flag: "🇹🇱", name: "Восточный Тимор" },
{ keys: ["tr", "turkey", "турция", "анкара"], flag: "🇹🇷", name: "Турция" },
{ keys: ["tm", "turkmenistan", "туркменистан", "ашхабад"], flag: "🇹🇲", name: "Туркменистан" },
{ keys: ["ae", "uae", "оаэ", "абудаби"], flag: "🇦🇪", name: "ОАЭ" },
{ keys: ["uz", "uzbekistan", "узбекистан", "ташкент"], flag: "🇺🇿", name: "Узбекистан" },
{ keys: ["vn", "vietnam", "вьетнам", "ханой"], flag: "🇻🇳", name: "Вьетнам" },
{ keys: ["ye", "yemen", "йемен", "сана"], flag: "🇾🇪", name: "Йемен" },
// Африка
{ keys: ["dz", "algeria", "алжир"], flag: "🇩🇿", name: "Алжир" },
{ keys: ["ao", "angola", "ангола", "луанда"], flag: "🇦🇴", name: "Ангола" },
{ keys: ["bj", "benin", "бенин", "порто-ново"], flag: "🇧🇯", name: "Бенин" },
{ keys: ["bw", "botswana", "ботсвана", "габороне"], flag: "🇧🇼", name: "Ботсвана" },
{ keys: ["bf", "burkina faso", "буркина-фасо", "уагадугу"], flag: "🇧🇫", name: "Буркина-Фасо" },
{ keys: ["bi", "burundi", "бурунди", "гитега"], flag: "🇧🇮", name: "Бурунди" },
{ keys: ["cv", "cape verde", "кабо-верде", "прая"], flag: "🇨🇻", name: "Кабо-Верде" },
{ keys: ["cm", "cameroon", "камерун", "яунде"], flag: "🇨🇲", name: "Камерун" },
{ keys: ["cf", "car", "цар", "банги"], flag: "🇨🇫", name: "ЦАР" },
{ keys: ["td", "chad", "чад", "нджамена"], flag: "🇹🇩", name: "Чад" },
{ keys: ["km", "comoros", "коморы", "морони"], flag: "🇰🇲", name: "Коморы" },
{ keys: ["cg", "congo", "конго", "браззавиль"], flag: "🇨🇬", name: "Республика Конго" },
{ keys: ["cd", "dr congo", "др конго", "киншаса"], flag: "🇨🇩", name: "ДР Конго" },
{ keys: ["ci", "cote d'ivoire", "кот-д'ивуар", "ямусукро"], flag: "🇨🇮", name: "Кот-д'Ивуар" },
{ keys: ["dj", "djibouti", "джибути"], flag: "🇩🇯", name: "Джибути" },
{ keys: ["eg", "egypt", "египет", "каир"], flag: "🇪🇬", name: "Египет" },
{ keys: ["gq", "eq guinea", "экваториальная гвинея", "малабо"], flag: "🇬🇶", name: "Экваториальная Гвинея" },
{ keys: ["er", "eritrea", "эритрея", "асмэра"], flag: "🇪🇷", name: "Эритрея" },
{ keys: ["sz", "eswatini", "эсватини", "мбабане"], flag: "🇸🇿", name: "Эсватини" },
{ keys: ["et", "ethiopia", "эфиопия", "аддис-абеба"], flag: "🇪🇹", name: "Эфиопия" },
{ keys: ["ga", "gabon", "габон", "либревиль"], flag: "🇬🇦", name: "Габон" },
{ keys: ["gm", "gambia", "гамбия", "банжул"], flag: "🇬🇲", name: "Гамбия" },
{ keys: ["gh", "ghana", "гана", "аккра"], flag: "🇬🇭", name: "Гана" },
{ keys: ["gn", "guinea", "гвинея", "конакри"], flag: "🇬🇳", name: "Гвинея" },
{ keys: ["gw", "guinea-bissau", "гвинея-бисау", "бисау"], flag: "🇬🇼", name: "Гвинея-Бисау" },
{ keys: ["ke", "kenya", "кения", "найроби"], flag: "🇰🇪", name: "Кения" },
{ keys: ["ls", "lesotho", "лесото", "масеру"], flag: "🇱🇸", name: "Лесото" },
{ keys: ["lr", "liberia", "либерия", "монровия"], flag: "🇱🇷", name: "Либерия" },
{ keys: ["ly", "libya", "ливия", "триполи"], flag: "🇱🇾", name: "Ливия" },
{ keys: ["mg", "madagascar", "мадагаскар", "антананариву"], flag: "🇲🇬", name: "Мадагаскар" },
{ keys: ["mw", "malawi", "малави", "лилонгве"], flag: "🇲🇼", name: "Малави" },
{ keys: ["ml", "mali", "мали", "бамако"], flag: "🇲🇱", name: "Мали" },
{ keys: ["mr", "mauritania", "мавритания", "нуакшот"], flag: "🇲🇷", name: "Мавритания" },
{ keys: ["mu", "mauritius", "маврикий", "порт-луи"], flag: "🇲🇺", name: "Маврикий" },
{ keys: ["ma", "morocco", "марокко", "рабат"], flag: "🇲🇦", name: "Марокко" },
{ keys: ["mz", "mozambique", "мозамбик", "мапуту"], flag: "🇲🇿", name: "Мозамбик" },
{ keys: ["na", "namibia", "намибия", "виндхук"], flag: "🇳🇦", name: "Намибия" },
{ keys: ["ne", "niger", "нигер", "ниамей"], flag: "🇳🇪", name: "Нигер" },
{ keys: ["ng", "nigeria", "нигерия", "абуджа"], flag: "🇳🇬", name: "Нигерия" },
{ keys: ["rw", "rwanda", "руанда", "кигали"], flag: "🇷🇼", name: "Руанда" },
{ keys: ["st", "sao tome", "сан-томе"], flag: "🇸🇹", name: "Сан-Томе и Принсипи" },
{ keys: ["sn", "senegal", "сенегал", "дакар"], flag: "🇸🇳", name: "Сенегал" },
{ keys: ["sc", "seychelles", "сейшелы", "виктория"], flag: "🇸🇨", name: "Сейшельские Острова" },
{ keys: ["sl", "sierra leone", "сьерра-леоне", "фридаун"], flag: "🇸🇱", name: "Сьерра-Леоне" },
{ keys: ["so", "somalia", "сомали", "могадишо"], flag: "🇸🇴", name: "Сомали" },
{ keys: ["za", "south africa", "юар", "претория"], flag: "🇿🇦", name: "ЮАР" },
{ keys: ["ss", "south sudan", "южный судан", "джуба"], flag: "🇸🇸", name: "Южный Судан" },
{ keys: ["sd", "sudan", "судан", "хартум"], flag: "🇸🇩", name: "Судан" },
{ keys: ["tz", "tanzania", "танзания", "додома"], flag: "🇹🇿", name: "Танзания" },
{ keys: ["tg", "togo", "того", "ломе"], flag: "🇹🇬", name: "Того" },
{ keys: ["tn", "tunisia", "тунис"], flag: "🇹🇳", name: "Тунис" },
{ keys: ["ug", "uganda", "уганда", "кампала"], flag: "🇺🇬", name: "Уганда" },
{ keys: ["zm", "zambia", "замбия", "лусака"], flag: "🇿🇲", name: "Замбия" },
{ keys: ["zw", "zimbabwe", "зимбабве", "хараре"], flag: "🇿🇼", name: "Зимбабве" },
// Северная и Южная Америка
{ keys: ["ag", "antigua", "антигуа", "сен-джонс"], flag: "🇦🇬", name: "Антигуа и Барбуда" },
{ keys: ["ar", "argentina", "аргентина", "буэнос-айрес"], flag: "🇦🇷", name: "Аргентина" },
{ keys: ["bs", "bahamas", "багамы", "нассау"], flag: "🇧🇸", name: "Багамы" },
{ keys: ["bb", "barbados", "барбадос", "бриджтаун"], flag: "🇧🇧", name: "Барбадос" },
{ keys: ["bz", "belize", "белиз", "бельмопан"], flag: "🇧🇿", name: "Белиз" },
{ keys: ["bo", "bolivia", "боливия", "сукре"], flag: "🇧🇴", name: "Боливия" },
{ keys: ["br", "brazil", "бразилия", "бразилиа"], flag: "🇧🇷", name: "Бразилия" },
{ keys: ["ca", "canada", "канада", "оттава"], flag: "🇨🇦", name: "Канада" },
{ keys: ["cl", "chile", "чили", "сантьяго"], flag: "🇨🇱", name: "Чили" },
{ keys: ["co", "colombia", "колумбия", "богота"], flag: "🇨🇴", name: "Колумбия" },
{ keys: ["cr", "costa rica", "коста-рика", "сан-хосе"], flag: "🇨🇷", name: "Коста-Рика" },
{ keys: ["cu", "cuba", "куба", "гавана"], flag: "🇨🇺", name: "Куба" },
{ keys: ["dm", "dominica", "доминика", "розо"], flag: "🇩🇲", name: "Доминика" },
{ keys: ["do", "dom rep", "доминикана", "санто-доминго"], flag: "🇩🇴", name: "Доминикана" },
{ keys: ["ec", "ecuador", "эквадор", "кито"], flag: "🇪🇨", name: "Эквадор" },
{ keys: ["sv", "el salvador", "сальвадор", "сан-сальвадор"], flag: "🇸🇻", name: "Сальвадор" },
{ keys: ["gd", "grenada", "гренада", "сен-джорджес"], flag: "🇬🇩", name: "Гренада" },
{ keys: ["gt", "guatemala", "гватемала"], flag: "🇬🇹", name: "Гватемала" },
{ keys: ["gy", "guyana", "гайана", "джорджтаун"], flag: "🇬🇾", name: "Гайана" },
{ keys: ["ht", "haiti", "гаити", "порт-о-пренс"], flag: "🇭🇹", name: "Гаити" },
{ keys: ["hn", "honduras", "гондурас", "тегусигальпа"], flag: "🇭🇳", name: "Гондурас" },
{ keys: ["jm", "jamaica", "ямайка", "кингстон"], flag: "🇯🇲", name: "Ямайка" },
{ keys: ["mx", "mexico", "мексика", "мехико"], flag: "🇲🇽", name: "Мексика" },
{ keys: ["ni", "nicaragua", "никарагуа", "манагуа"], flag: "🇳🇮", name: "Никарагуа" },
{ keys: ["pa", "panama", "панама"], flag: "🇵🇦", name: "Панама" },
{ keys: ["py", "paraguay", "парагвай", "асунсьон"], flag: "🇵🇾", name: "Парагвай" },
{ keys: ["pe", "peru", "перу", "лима"], flag: "🇵🇪", name: "Перу" },
{ keys: ["kn", "st kitts", "сент-кинс", "бассетр"], flag: "🇰🇳", name: "Сент-Китс и Невис" },
{ keys: ["lc", "st lucia", "сент-люсия", "кастри"], flag: "🇱🇨", name: "Сент-Люсия" },
{ keys: ["vc", "st vincent", "сент-винсент", "кингстаун"], flag: "🇻🇨", name: "Сент-Винсент и Гренадины" },
{ keys: ["sr", "suriname", "суринам", "парамарибо"], flag: "🇸🇷", name: "Суринам" },
{ keys: ["tt", "trinidad", "тринидад", "порт-оф-спейн"], flag: "🇹🇹", name: "Тринидад и Тобаго" },
{ keys: ["us", "usa", "сша", "вашингтон"], flag: "🇺🇸", name: "США" },
{ keys: ["uy", "uruguay", "уругвай", "монтевидео"], flag: "🇺🇾", name: "Уругвай" },
{ keys: ["ve", "venezuela", "венесуэла", "каракас"], flag: "🇻🇪", name: "Венесуэла" },
// Океания
{ keys: ["au", "australia", "австралия", "канберра"], flag: "🇦🇺", name: "Австралия" },
{ keys: ["fj", "fiji", "фиджи", "сува"], flag: "🇫🇯", name: "Фиджи" },
{ keys: ["ki", "kiribati", "кирибати", "южная тарава"], flag: "🇰🇮", name: "Кирибати" },
{ keys: ["mh", "marshall islands", "маршалловы острова", "маджуро"], flag: "🇲🇭", name: "Маршалловы Острова" },
{ keys: ["fm", "micronesia", "микронезия", "паликир"], flag: "🇫🇲", name: "Микронезия" },
{ keys: ["nr", "nauru", "науру", "барен"], flag: "🇳🇷", name: "Науру" },
{ keys: ["nz", "new zealand", "новая зеландия", "веллингтон"], flag: "🇳🇿", name: "Новая Зеландия" },
{ keys: ["pw", "palau", "палау", "нгерулмуд"], flag: "🇵🇼", name: "Палау" },
{ keys: ["pg", "papua new guinea", "папуа", "порт-морсби"], flag: "🇵🇬", name: "Папуа — Новая Гвинея" },
{ keys: ["ws", "samoa", "самоа", "апиа"], flag: "🇼🇸", name: "Самоа" },
{ keys: ["sb", "solomon islands", "соломоновы острова", "хониара"], flag: "🇸🇧", name: "Соломоновы Острова" },
{ keys: ["to", "tonga", "тонга", "нукуалофа"], flag: "🇹🇴", name: "Тонга" },
{ keys: ["tv", "tuvalu", "тувалу", "фунафути"], flag: "🇹🇻", name: "Тувалу" },
{ keys: ["vu", "vanuatu", "вануату", "порт-вила"], flag: "🇻🇺", name: "Вануату" }
];

// 🐛 ФИКС "ВСЁ РУМЫНИЯ": ключи вроде "ro" (Румыния), "us" (США), "at" (Австрия)
// и т.п. — это двухбуквенные ISO-коды, и раньше матчинг шёл простым
// text.includes(key). "ro" — обычная подстрока внутри "provider", "protocol",
// "europe", "proxy", "micro" и т.д., поэтому Румыния матчилась почти на любом
// хостнейме раньше, чем доходило до реального совпадения. Для коротких кодов
// (≤3 символов) теперь требуем границу токена (начало/конец строки, точка,
// дефис, цифра, подчёркивание) с обеих сторон — так "ro1.example.com" или
// "server-ro.net" матчатся, а "provider.com" — нет. Длинные ключи (полные
// названия стран/городов) — как и раньше, обычным substring-поиском, там риск
// случайного совпадения пренебрежимо мал.
export function matchesCountryKey(text, key) {
  if (!text || !key) return false;
  if (key.length <= 3) {
    const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`(^|[^a-zа-я])${escaped}(?![a-zа-я])`, "i");
    return re.test(text);
  }
  return text.includes(key);
}

// Единая точка определения страны по тексту (название сервера после # или
// хост в самой ссылке) — используется и в commands.js (detectCountry), и в
// index.js (applyRename), чтобы логика матчинга не дублировалась и не
// расходилась между двумя копиями.
export function detectCountryFromText(text) {
  if (!text) return null;
  const lower = text.toLowerCase();
  for (const c of COUNTRIES) {
    if (c.keys.some((k) => matchesCountryKey(lower, k))) return c;
  }
  return null;
}
